package com.example.projectapp;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.SQLException;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DBClass extends SQLiteOpenHelper {
    private  static  final String dname= "NutritionDatabase";
    private static final int version =4;
    private SQLiteDatabase database;

    public DBClass(Context context){
        super(context, dname,null, version);
    }

    @Override
    public void onConfigure(SQLiteDatabase db) {
        db.setForeignKeyConstraintsEnabled(true);
        super.onConfigure(db);
    }
    @Override
    public void onCreate(SQLiteDatabase db) {
        try {
            String gender_cat = "CREATE TABLE  gender_group" +
                    "(id INTEGER PRIMARY KEY," +
                    "name VARCHAR )";
            db.execSQL(gender_cat);

            String foodtbl = "CREATE TABLE foods" +
                    "(id INTEGER PRIMARY KEY AUTOINCREMENT," +
                    "age VARCHAR ," +
                    "gender_cat INTEGER NOT NULL," +
                    "food VARCHAR," +
                    "FOREIGN KEY (gender_cat) REFERENCES gender_group(id))";
            db.execSQL(foodtbl);


            InsertGenderCat(1,"Men",db);
            InsertGenderCat(2,"Women",db);
            InsertGenderCat(3,"Toddlers",db);
            InsertGenderCat(4,"Olders",db);


            insertFoods("1",3, "Total Caloreis Required : \n100 Calories per kg.  \n\n Protein \n  1.2 grams per kg.  \n\n Breads  :\n 1/4 cup pasta, potatoes, or rice.\n 1/2 to 1 slice bread.\n  \nFruits:\n 1/4 cup pureed frui. \n 1/4 cup juice.  \n\n  Meat Substitutes:\n 1 egg. 1 Tbsp peanut butter (after age 2). 1 ounce meat, fish, or poultry. 1/4 cup cooked dried beans or legumes. 3/4 ounce cheese.\n\n Milk or Yogurt:\n 1/2 to 3/4 cup",db);
            insertFoods("2",3, "Total Caloreis Required: \n100 Calories per kg.  \n\n Protein \n  1.2 grams per kg.  \n\n Breads :\n 1/4 cup pasta, potatoes, or rice.\n 1/2 to 1 slice bread.\n  \nFruits:\n 1/4 cup pureed frui. \n 1/4 cup juice.  \n\n  Meat Substitutes:\n 1 egg. 1 Tbsp peanut butter (after age 2). 1 ounce meat, fish, or poultry. 1/4 cup cooked dried beans or legumes. 3/4 ounce cheese.\n\n Milk or Yogurt:\n 1/2 to 3/4 cup",db);
            insertFoods("4" ,3, "Total Caloreis Required : \n90 Calories per kg.\n\n Protein \n 1.1 grams per kg. \n \n Breads :\n 1/2 cup pasta, potatoes, or rice. \n 1 slice bread \n 3/4 ounce dry cereal. \n\n Fruits:\n 1/4 to 1/2 cup canned fruit. 1/2 piece fresh fruit. 1/2 cup juice.\n\n Meat / Meat Substitutes:\n 1 egg . 1 to 2 Tbsps peanut butter.  to 2 ounces meat, fish, or poultry. \n\n Milk or Yogurt:\n 3/4 cup\n\n Fats: 1 tsp \n\n Sweets and Desserts:\n 3 to 4 servings per week at the most",db);
            insertFoods("5" ,3, "Total Caloreis Required : \n90 Calories per kg.\n\n Protein \n 1.1 grams per kg. \n \n Breads:\n 1/2 cup pasta, potatoes, or rice. \n 1 slice bread \n 3/4 ounce dry cereal. \n\n Fruits:\n 1/4 to 1/2 cup canned fruit. 1/2 piece fresh fruit. 1/2 cup juice.\n\n Meat / Meat Substitutes:\n 1 egg . 1 to 2 Tbsps peanut butter.  to 2 ounces meat, fish, or poultry. \n\n Milk or Yogurt:\n 3/4 cup\n\n Fats: 1 tsp \n\n Sweets and Desserts:\n 3 to 4 servings per week at the most",db);
            insertFoods("6" ,3, "Total Caloreis Required : \n90 Calories per kg.\n\n Protein \n 1.1 grams per kg. \n \n Breads :\n 1/2 cup pasta, potatoes, or rice. \n 1 slice bread \n 3/4 ounce dry cereal. \n\n Fruits:\n 1/4 to 1/2 cup canned fruit. 1/2 piece fresh fruit. 1/2 cup juice.\n\n Meat / Meat Substitutes:\n 1 egg . 1 to 2 Tbsps peanut butter.  to 2 ounces meat, fish, or poultry. \n\n Milk or Yogurt:\n 3/4 cup\n\n Fats: 1 tsp \n\n Sweets and Desserts:\n 3 to 4 servings per week at the most",db);
            insertFoods("7", 3,"Total Caloreis Required : \n70 calories per kg \n\n Protein \n 1 gram per kg. \\n\\\\n Breads / Starches:\\\\n 1 cup pasta, potatoes, or rice.\\\\n 2 slices bread.\\\\n Fruits:\\\\n 1 cup canned fruit.\\\\n 1 piece fresh fruit.1/2 cup juice.\\\\nMeat / Meat Substitutes: \\\\n 1 egg \\\\n  Tbsps peanut butter .\\\\n 2 to 3 ounces meat, fish, or poultry.\\\\n\\\\n Milk or Yogurt:\\\\n\\\\n 1 cup.\\\\n\\\\n Fats:\\\\n  1 Tbsp",db);
            insertFoods("8", 3,"Total Caloreis Required\n :70 calories per kg \n\n Protein\n 1 gram per kg. \\\\n\\\\n Breads / Starches:\\\\n 1 cup pasta, potatoes, or rice.\\\\n 2 slices bread.\\\\n Fruits:\\\\n 1 cup canned fruit.\\\\n 1 piece fresh fruit.1/2 cup juice.\\\\nMeat / Meat Substitutes: \\\\n 1 egg \\\\n  Tbsps peanut butter .\\\\n 2 to 3 ounces meat, fish, or poultry.\\\\n\\\\n Milk or Yogurt:\\\\n\\\\n 1 cup.\\\\n\\\\n Fats:\\\\n  1 Tbsp",db);
            insertFoods("9", 3,"Total Caloreis Required\n :70 calories per kg \n\n Protein \n 1 gram per kg.\n\n Breads or Starches:\n 1 cup pasta, potatoes, or rice.\n 2 slices bread.\n\n Fruits:\n 1 cup canned fruit.\n 1 piece fresh fruit.1/2 cup juice.\n\n Meat or Meat Substitutes: \n 1 egg \n  Tbsps peanut butter .\n 2 to 3 ounces meat, fish, or poultry.\n\n Milk or Yogurt:\n 1 cup.\n\n Fats:\n  1 Tbsp",db);
            insertFoods("10",3,"Total Caloreis Required\n :70 calories per kg. \n\n Protein \n 1 gram per kg. \n\n Breads or Starches:\n 1 cup pasta, potatoes, or rice.\n 2 slices bread.\n\n Fruits:\n 1 cup canned fruit.\n 1 piece fresh fruit.1/2 cup juice.\n\nMeat or Meat Substitutes: \n 1 egg \n  Tbsps peanut butter .\n 2 to 3 ounces meat, fish, or poultry.\n\n Milk or Yogurt:\n 1 cup.\n\n Fats:\n  1 Tbsp",db);
            insertFoods("11",3,"Total Caloreis Required\n :70 calories per kg \n\n Protein \n 1 gram per kg. \n\n Breads or Starches:\n 1 cup pasta, potatoes, or rice.\n 2 slices bread.\n\n Fruits:\n 1 cup canned fruit.\n 1 piece fresh fruit.1/2 cup juice.\nMeat or Meat Substitutes: \n 1 egg \n  Tbsps peanut butter .\n 2 to 3 ounces meat, fish, or poultry.\n\n Milk or Yogurt:\n\n 1 cup.\n\n Fats:\n  1 Tbsp",db);


            insertFoods("12",2,"Calories Required \n 45 to 55 calories per kg.\n\n Protein \n 1 gram per kg. \n\n Breads or Starches. \n 1 bagel or muffin.\n 2 slices bread.\n 1/2 cup cooked cereal, pasta, potatoes, or rice. \n\n Fruits:\n 1/2 cup canned fruit or fruit juice. \n 1 piece fresh fruit, such as an apple, orange, peach, or pear. \n\n 15 to 20 grapes.\n\n Meat or Meat Substitutes:\n 1/2 cup cottage or ricotta cheese. \n 3/4 to 1 cup cooked dried beans or legumes. \n 1 egg.\n 2 to 3 ounces meat, fish, or poultry.\n\n  Milk or Yogurt\n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable. \n 2 cups salad greens. \n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\nSweets and Desserts .",db);
            insertFoods("13",2,"Calories Required \n 45 to 55 calories per kg.\n\n Protein \n 1 gram per kg. \n\n Breads or Starches. \n 1 bagel or muffin.\n 2 slices bread.\n 1/2 cup cooked cereal, pasta, potatoes, or rice. \n\n Fruits:\n 1/2 cup canned fruit or fruit juice. \n 1 piece fresh fruit, such as an apple, orange, peach, or pear. \n\n 15 to 20 grapes.\n\n Meat or Meat Substitutes:\n 1/2 cup cottage or ricotta cheese. \n 3/4 to 1 cup cooked dried beans or legumes. \n 1 egg.\n 2 to 3 ounces meat, fish, or poultry.\n\n  Milk or Yogurt\n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable. \n 2 cups salad greens. \n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\nSweets and Desserts .",db);
            insertFoods("14",2,"Calories Required \n 45 to 55 calories per kg.\n\n Protein \n 1 gram per kg. \n\n Breads or Starches. \n 1 bagel or muffin.\n 2 slices bread.\n 1/2 cup cooked cereal, pasta, potatoes, or rice. \n\n Fruits:\n 1/2 cup canned fruit or fruit juice. \n 1 piece fresh fruit, such as an apple, orange, peach, or pear. \n\n 15 to 20 grapes.\n\n Meat or Meat Substitutes:\n 1/2 cup cottage or ricotta cheese. \n 3/4 to 1 cup cooked dried beans or legumes. \n 1 egg.\n 2 to 3 ounces meat, fish, or poultry.\n\n  Milk or Yogurt\n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable. \n 2 cups salad greens. \n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\nSweets and Desserts .",db);
            insertFoods("15",2,"Total Calories Required \n 40 to 45 calories per kg.\n\n Protein \n 0.9 grams per kg. \n\n Breads or Starches::1/2 cup cottage or ricotta cheese.3/4 to 1 cup cooked dried beans or legumes.\n 1 egg.2 to 3 ounces meat, fish, or poultry.\n  Milk or Yogurt \n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable.\n 2 cups salad greens.\n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\n Sweets and Desserts .",db);
            insertFoods("16",2,"Total Calories Required \n 40 to 45 calories per kg.\n\n Protein \n 0.9 grams per kg. \n\n Breads or Starches::1/2 cup cottage or ricotta cheese.3/4 to 1 cup cooked dried beans or legumes.\n 1 egg.2 to 3 ounces meat, fish, or poultry.\n  Milk or Yogurt \n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable.\n 2 cups salad greens.\n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\n Sweets and Desserts .",db);
            insertFoods("17",2,"Total Calories Required \n 40 to 45 calories per kg.\n\n Protein \n 0.9 grams per kg. \n\n Breads or Starches::1/2 cup cottage or ricotta cheese.3/4 to 1 cup cooked dried beans or legumes.\n 1 egg.2 to 3 ounces meat, fish, or poultry.\n  Milk or Yogurt \n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable.\n 2 cups salad greens.\n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\n Sweets and Desserts .",db);
            insertFoods("18",2,"Total Calories Required \n 40 to 45 calories per kg.\n\n Protein \n 0.9 grams per kg. \n\n Breads or Starches::1/2 cup cottage or ricotta cheese.3/4 to 1 cup cooked dried beans or legumes.\n 1 egg.2 to 3 ounces meat, fish, or poultry.\n  Milk or Yogurt \n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable.\n 2 cups salad greens.\n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\n Sweets and Desserts .",db);
            insertFoods("19",2,"Total Calories Required \n 40 to 45 calories per kg.\n\n Protein \n 0.9 grams per kg. \n\n Breads or Starches::1/2 cup cottage or ricotta cheese.3/4 to 1 cup cooked dried beans or legumes.\n 1 egg.2 to 3 ounces meat, fish, or poultry.\n  Milk or Yogurt \n 1 cup  milk or yogurt.\n\n Vegetables:\n 1/2 cup cooked or 1 cup raw vegetable.\n 2 cups salad greens.\n\n Fats\n 6 almonds or 10 peanuts.\n 2 Tbsps cream cheese, avocado, or low calorie salad dressing.\n\n Sweets and Desserts .",db);
            insertFoods("20", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("21", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("22", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("23", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("24", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("25", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("26", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("27", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("28", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("29", 2,"Carbohydrates\n  Sweet potatoes, quinoa, and brown rice are good source of Carbohydrates. \n\n Nuts and Seeds\n \n\n Calcium Rich Foods \n Calcium-rich foods include sesame seeds, leafy dark greens, oranges, broccoli, and calcium-fortified foods like cereal and bread.\n\n Hormone-Balancing Foods \n Foods like blueberries, yogurt, walnuts, and oatmeal are good Hormone-Balancing Foods. \n\n Liver Cleanses \n Cleansing the liver with lemon juice, garlic, and onions can go a long way with keeping you healthy in the long run. \n\n Iron \n Iron can be get  from foods such as dried beans, eggs including the yolks, liver, lean red meat, poultry, salmon, tuna, oysters, almonds, tofu, and whole grains. \n\n Protein. ",db);
            insertFoods("30", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("31", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("32", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("33", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("34", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("35", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("36", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("37", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("38", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("39", 2,"Super FoodsSuper\n Supper foods are essential, especially olive oil. They’re rich in polyphenols, which are powerful brain protective antioxidants. Coconut oil, wild salmon, blueberries, turmeric, eggs, dandelion greens, and walnuts.\n\n Bok Choy \n Bok choy is low in calories, making this vegetable a winner for weight loss in your thirties. It keeps blood pressure in the normal range, improves digestion, is rich in folate, and is an important nutrient in pregnancy and breastfeeding.\n\n Antioxidants \n  Antioxidants keep  natural aging process as slow as possible, eat tons of antioxidants. Berries, tropical fruit, colorful vegetables, and green leafy vegetables are among the most antioxidant-rich foods.  \n\n Fatty Fish and Eggs. \n\n Folic Acid\n Leafy greens are full of folic acid and antioxidants. \n\n  Low-Fat Dairy \n Low-fat choices  milk, cheese, yogurt and cottage chees. \n\n  Vitamin E \n Vitamin E is essential for fertility in male and females. “Avocados and pine nuts are rich in vitamin E, which is important for reproduction. \n\n  ",db);
            insertFoods("40", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("41", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("42", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("43", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("44", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("45", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("46", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("47", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("48", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("49", 2," Heart-Healthy Foods \n Eat foods that promote a healthy cardiovascular system,Garlic, onions, leek, turmeric, olives, flax seed oil, and green leafy veggies are among the best foods for this.\n\n Whole Grains \n whole grains like whole wheat, brown rice, and oats to help keep blood pressure and cholesterol in check. \n\n Omega-3 \n  Take 3g-5g of liquid fish oil daily to get omega-3. \n\n Seaweed and Sunflower Seeds. \n\n   Coconut \n\n Artichokes",db);
            insertFoods("50",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("51",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("52",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("53",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("54",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("55",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("56",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("57",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("58",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);
            insertFoods("59",2,"High Fiber Veggies \n The high fiber founds are cabbage, broccoli or Brusse . \n\n Turmeric\n Zinc \n Eat Zinc foods. \n\n Plant-Based Protein \n Whole grains, lentils and beans provide some of the best sources of plant-based protein, as well as an array of healthy nutrients. \n\n B-Vitamins \n Eggs, fish, chicken ,bananas, potatoes, and pomegranates are high in B-Vitamins. \n\n Eggs. \n\n Basil.\n\n Brazil Nuts.\n\n Brazil nuts are filled with vitamins and nutrients that support so many important functions as you get older. They contain selenium, calcium, iron, copper, magnesium, manganese, potassium, phosphorus, zinc, and fiber.",db);


            }
        catch (SQLException e){
            e.printStackTrace();
        }

    }


    private void  InsertGenderCat(Integer id, String group, SQLiteDatabase db){
        ContentValues values = new ContentValues();
        values.put("id",id);
        values.put("name",group);
        db.insert("gender_group", null,values);
    }
    private  void  insertFoods(String age,Integer cat, String food,  SQLiteDatabase db){
        ContentValues values = new ContentValues();
        values.put("age",age);
        values.put("gender_cat",cat);
        values.put("food",food);
        db.insert("foods", null,values);
    }



    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        String genderTbl  ="DROP TABLE IF EXISTS gender_categories";
        db.execSQL(genderTbl);
        String foodsTbl  ="DROP TABLE IF EXISTS foods";
        db.execSQL(foodsTbl);


    }


}
